name: currency_picker_plus
description: Enhanced and customizable Flutter currency picker widget with extra features.
maintainer: Johan Esteban
version: 1.1.2
repository: https://github.com/nekomaruh/currency_picker_plus
homepage: https://github.com/nekomaruh/currency_picker_plus
license: MIT

topics:
  - currency
  - picker
  - money
  - currency-formatter
  - currency-picker

environment:
  sdk: ^3.8.1

dependencies:
  flutter_svg: ^2.2.0
  decimal: ^3.2.4
  intl: ^0.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  test_coverage_badge: ^0.3.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags_svg/
